# Generated by Django 4.0.4 on 2022-04-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=255)),
                ('food', models.CharField(max_length=255)),
                ('star', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
